name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2022.3.18f1
          targetPlatform: StandaloneWindows64
          projectPath: DortmundCitySandbox
          buildName: DortmundCitySandbox
      - uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2022.3.18f1
          targetPlatform: WebGL
          projectPath: DortmundCitySandbox
          buildName: DortmundCitySandbox
      - name: Zip Windows build
        run: |
          mkdir -p release
          cd build/StandaloneWindows64
          zip -r ../../release/DortmundCitySandbox-win64.zip .
      - name: Prepare WebGL bundle
        run: |
          mkdir -p release
          tar -czf release/DortmundCitySandbox-webgl.tar.gz -C build/WebGL .
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/DortmundCitySandbox-win64.zip
            release/DortmundCitySandbox-webgl.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify Discord
        if: success()
        run: |
          if [ -n "${{ secrets.DISCORD_WEBHOOK_URL }}" ]; then
            curl -H 'Content-Type: application/json'               -d "{"content":"🚀 Dortmund City Sandbox ${{ github.ref }} veröffentlicht"}"               "${{ secrets.DISCORD_WEBHOOK_URL }}";
          fi
